// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/sync.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Payload struct {
	Acks                 [][]byte   `protobuf:"bytes,1,rep,name=acks,proto3" json:"acks,omitempty"`
	Offers               [][]byte   `protobuf:"bytes,2,rep,name=offers,proto3" json:"offers,omitempty"`
	Requests             [][]byte   `protobuf:"bytes,3,rep,name=requests,proto3" json:"requests,omitempty"`
	Messages             []*Message `protobuf:"bytes,4,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Payload) Reset()         { *m = Payload{} }
func (m *Payload) String() string { return proto.CompactTextString(m) }
func (*Payload) ProtoMessage()    {}
func (*Payload) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dca527c092c79d7, []int{0}
}

func (m *Payload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload.Unmarshal(m, b)
}
func (m *Payload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload.Marshal(b, m, deterministic)
}
func (m *Payload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload.Merge(m, src)
}
func (m *Payload) XXX_Size() int {
	return xxx_messageInfo_Payload.Size(m)
}
func (m *Payload) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload.DiscardUnknown(m)
}

var xxx_messageInfo_Payload proto.InternalMessageInfo

func (m *Payload) GetAcks() [][]byte {
	if m != nil {
		return m.Acks
	}
	return nil
}

func (m *Payload) GetOffers() [][]byte {
	if m != nil {
		return m.Offers
	}
	return nil
}

func (m *Payload) GetRequests() [][]byte {
	if m != nil {
		return m.Requests
	}
	return nil
}

func (m *Payload) GetMessages() []*Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

type Metadata struct {
	Parents              []byte   `protobuf:"bytes,1,opt,name=parents,proto3" json:"parents,omitempty"`
	NoAckRequired        bool     `protobuf:"varint,2,opt,name=no_ack_required,json=noAckRequired,proto3" json:"no_ack_required,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dca527c092c79d7, []int{1}
}

func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata.Unmarshal(m, b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
}
func (m *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(m, src)
}
func (m *Metadata) XXX_Size() int {
	return xxx_messageInfo_Metadata.Size(m)
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetParents() []byte {
	if m != nil {
		return m.Parents
	}
	return nil
}

func (m *Metadata) GetNoAckRequired() bool {
	if m != nil {
		return m.NoAckRequired
	}
	return false
}

type Message struct {
	GroupId              []byte    `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Timestamp            int64     `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Body                 []byte    `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Metadata             *Metadata `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dca527c092c79d7, []int{2}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetGroupId() []byte {
	if m != nil {
		return m.GroupId
	}
	return nil
}

func (m *Message) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Message) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Message) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func init() {
	proto.RegisterType((*Payload)(nil), "vac.mvds.Payload")
	proto.RegisterType((*Metadata)(nil), "vac.mvds.Metadata")
	proto.RegisterType((*Message)(nil), "vac.mvds.Message")
}

func init() { proto.RegisterFile("protobuf/sync.proto", fileDescriptor_2dca527c092c79d7) }

var fileDescriptor_2dca527c092c79d7 = []byte{
	// 278 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x50, 0xcd, 0x4a, 0xc4, 0x30,
	0x10, 0x26, 0xdb, 0x65, 0x37, 0xce, 0xae, 0x88, 0x23, 0x48, 0x14, 0x0f, 0x65, 0x0f, 0xd2, 0x8b,
	0x15, 0xd6, 0x27, 0xd0, 0x9b, 0xe0, 0x82, 0xe4, 0xe8, 0xa5, 0xa4, 0x4d, 0xba, 0x94, 0xda, 0xa6,
	0x26, 0xe9, 0x42, 0x6f, 0x9e, 0x7c, 0x6e, 0x69, 0xfa, 0xa3, 0xb7, 0xef, 0x67, 0x66, 0xbe, 0x99,
	0x81, 0xab, 0xc6, 0x68, 0xa7, 0xd3, 0x36, 0x7f, 0xb4, 0x5d, 0x9d, 0xc5, 0x9e, 0x21, 0x3d, 0x89,
	0x2c, 0xae, 0x4e, 0xd2, 0xee, 0xbe, 0x09, 0xac, 0xdf, 0x45, 0xf7, 0xa9, 0x85, 0x44, 0x84, 0xa5,
	0xc8, 0x4a, 0xcb, 0x48, 0x18, 0x44, 0x5b, 0xee, 0x31, 0x5e, 0xc3, 0x4a, 0xe7, 0xb9, 0x32, 0x96,
	0x2d, 0xbc, 0x3a, 0x32, 0xbc, 0x05, 0x6a, 0xd4, 0x57, 0xab, 0xac, 0xb3, 0x2c, 0xf0, 0xce, 0xcc,
	0xf1, 0x01, 0x68, 0xa5, 0xac, 0x15, 0x47, 0x65, 0xd9, 0x32, 0x0c, 0xa2, 0xcd, 0xfe, 0x32, 0x9e,
	0x02, 0xe3, 0xc3, 0xe0, 0xf0, 0xb9, 0x64, 0xf7, 0x06, 0xf4, 0xa0, 0x9c, 0x90, 0xc2, 0x09, 0x64,
	0xb0, 0x6e, 0x84, 0x51, 0xb5, 0xeb, 0xb7, 0x20, 0xd1, 0x96, 0x4f, 0x14, 0xef, 0xe1, 0xa2, 0xd6,
	0x89, 0xc8, 0xca, 0xa4, 0xcf, 0x29, 0x8c, 0x92, 0x6c, 0x11, 0x92, 0x88, 0xf2, 0xf3, 0x5a, 0x3f,
	0x67, 0x25, 0x1f, 0xc5, 0xdd, 0x0f, 0x81, 0xf5, 0x98, 0x81, 0x37, 0x40, 0x8f, 0x46, 0xb7, 0x4d,
	0x52, 0xc8, 0x69, 0x9c, 0xe7, 0xaf, 0x12, 0xef, 0xe0, 0xcc, 0x15, 0x95, 0xb2, 0x4e, 0x54, 0x8d,
	0x1f, 0x14, 0xf0, 0x3f, 0xa1, 0xff, 0x44, 0xaa, 0x65, 0xc7, 0x02, 0xdf, 0xe4, 0x31, 0xc6, 0xfd,
	0x55, 0xc3, 0x9a, 0x6c, 0x19, 0x92, 0x68, 0xb3, 0xc7, 0xff, 0x57, 0x0d, 0x0e, 0x9f, 0x6b, 0x5e,
	0xe0, 0x83, 0x4e, 0xaf, 0x4f, 0x57, 0x1e, 0x3d, 0xfd, 0x06, 0x00, 0x00, 0xff, 0xff, 0x36, 0x00,
	0xbf, 0x93, 0x8d, 0x01, 0x00, 0x00,
}
