// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/sync.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Payload struct {
	Ack                  *Ack       `protobuf:"bytes,1,opt,name=ack,proto3" json:"ack,omitempty"`
	Offer                *Offer     `protobuf:"bytes,2,opt,name=offer,proto3" json:"offer,omitempty"`
	Request              *Request   `protobuf:"bytes,3,opt,name=request,proto3" json:"request,omitempty"`
	Messages             []*Message `protobuf:"bytes,4,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Payload) Reset()         { *m = Payload{} }
func (m *Payload) String() string { return proto.CompactTextString(m) }
func (*Payload) ProtoMessage()    {}
func (*Payload) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dca527c092c79d7, []int{0}
}

func (m *Payload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payload.Unmarshal(m, b)
}
func (m *Payload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payload.Marshal(b, m, deterministic)
}
func (m *Payload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payload.Merge(m, src)
}
func (m *Payload) XXX_Size() int {
	return xxx_messageInfo_Payload.Size(m)
}
func (m *Payload) XXX_DiscardUnknown() {
	xxx_messageInfo_Payload.DiscardUnknown(m)
}

var xxx_messageInfo_Payload proto.InternalMessageInfo

func (m *Payload) GetAck() *Ack {
	if m != nil {
		return m.Ack
	}
	return nil
}

func (m *Payload) GetOffer() *Offer {
	if m != nil {
		return m.Offer
	}
	return nil
}

func (m *Payload) GetRequest() *Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *Payload) GetMessages() []*Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

type Ack struct {
	Ids                  [][]byte `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ack) Reset()         { *m = Ack{} }
func (m *Ack) String() string { return proto.CompactTextString(m) }
func (*Ack) ProtoMessage()    {}
func (*Ack) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dca527c092c79d7, []int{1}
}

func (m *Ack) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ack.Unmarshal(m, b)
}
func (m *Ack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ack.Marshal(b, m, deterministic)
}
func (m *Ack) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ack.Merge(m, src)
}
func (m *Ack) XXX_Size() int {
	return xxx_messageInfo_Ack.Size(m)
}
func (m *Ack) XXX_DiscardUnknown() {
	xxx_messageInfo_Ack.DiscardUnknown(m)
}

var xxx_messageInfo_Ack proto.InternalMessageInfo

func (m *Ack) GetIds() [][]byte {
	if m != nil {
		return m.Ids
	}
	return nil
}

type Message struct {
	GroupId              []byte   `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Body                 []byte   `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dca527c092c79d7, []int{2}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetGroupId() []byte {
	if m != nil {
		return m.GroupId
	}
	return nil
}

func (m *Message) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Message) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type Offer struct {
	Ids                  [][]byte `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Offer) Reset()         { *m = Offer{} }
func (m *Offer) String() string { return proto.CompactTextString(m) }
func (*Offer) ProtoMessage()    {}
func (*Offer) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dca527c092c79d7, []int{3}
}

func (m *Offer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Offer.Unmarshal(m, b)
}
func (m *Offer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Offer.Marshal(b, m, deterministic)
}
func (m *Offer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Offer.Merge(m, src)
}
func (m *Offer) XXX_Size() int {
	return xxx_messageInfo_Offer.Size(m)
}
func (m *Offer) XXX_DiscardUnknown() {
	xxx_messageInfo_Offer.DiscardUnknown(m)
}

var xxx_messageInfo_Offer proto.InternalMessageInfo

func (m *Offer) GetIds() [][]byte {
	if m != nil {
		return m.Ids
	}
	return nil
}

type Request struct {
	Ids                  [][]byte `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_2dca527c092c79d7, []int{4}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetIds() [][]byte {
	if m != nil {
		return m.Ids
	}
	return nil
}

func init() {
	proto.RegisterType((*Payload)(nil), "mvds.Payload")
	proto.RegisterType((*Ack)(nil), "mvds.Ack")
	proto.RegisterType((*Message)(nil), "mvds.Message")
	proto.RegisterType((*Offer)(nil), "mvds.Offer")
	proto.RegisterType((*Request)(nil), "mvds.Request")
}

func init() { proto.RegisterFile("protobuf/sync.proto", fileDescriptor_2dca527c092c79d7) }

var fileDescriptor_2dca527c092c79d7 = []byte{
	// 257 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x15, 0x9c, 0xe2, 0xf4, 0x1a, 0x24, 0x74, 0x0c, 0xb8, 0x2a, 0x43, 0xc8, 0x42, 0x59,
	0x82, 0x04, 0x4f, 0x50, 0x36, 0x06, 0x04, 0xf2, 0xc0, 0xc0, 0x82, 0x9c, 0xd8, 0xa9, 0xa2, 0x10,
	0x1c, 0xe2, 0x04, 0x29, 0x0f, 0xc3, 0xbb, 0xa2, 0x9c, 0x5b, 0x3a, 0xc0, 0x76, 0xf7, 0x7d, 0xbf,
	0xe4, 0xff, 0x0c, 0x67, 0x6d, 0x67, 0x7b, 0x9b, 0x0f, 0xe5, 0x8d, 0x1b, 0x3f, 0x8a, 0x8c, 0x36,
	0x0c, 0x9b, 0x2f, 0xed, 0xd2, 0xef, 0x00, 0xf8, 0xb3, 0x1a, 0xdf, 0xad, 0xd2, 0xb8, 0x02, 0xa6,
	0x8a, 0x5a, 0x04, 0x49, 0xb0, 0x5e, 0xdc, 0xce, 0xb3, 0xc9, 0x67, 0x9b, 0xa2, 0x96, 0x13, 0xc5,
	0x4b, 0x98, 0xd9, 0xb2, 0x34, 0x9d, 0x38, 0x22, 0xbd, 0xf0, 0xfa, 0x69, 0x42, 0xd2, 0x1b, 0xbc,
	0x02, 0xde, 0x99, 0xcf, 0xc1, 0xb8, 0x5e, 0x30, 0x0a, 0x9d, 0xf8, 0x90, 0xf4, 0x50, 0xee, 0x2d,
	0x5e, 0x43, 0xd4, 0x18, 0xe7, 0xd4, 0xd6, 0x38, 0x11, 0x26, 0xec, 0x90, 0x7c, 0xf4, 0x54, 0xfe,
	0xea, 0xf4, 0x1c, 0xd8, 0xa6, 0xa8, 0xf1, 0x14, 0x58, 0xa5, 0x9d, 0x08, 0x12, 0xb6, 0x8e, 0xe5,
	0x34, 0xa6, 0x2f, 0xc0, 0x77, 0x69, 0x5c, 0x42, 0xb4, 0xed, 0xec, 0xd0, 0xbe, 0x55, 0x9a, 0xca,
	0xc7, 0x92, 0xd3, 0xfe, 0xa0, 0xf1, 0x02, 0xe6, 0x7d, 0xd5, 0x18, 0xd7, 0xab, 0xa6, 0xa5, 0xe6,
	0x4c, 0x1e, 0x00, 0x22, 0x84, 0xb9, 0xd5, 0x23, 0xb5, 0x8d, 0x25, 0xcd, 0xe9, 0x12, 0x66, 0x74,
	0xd4, 0x3f, 0x4f, 0xae, 0x80, 0xef, 0x4e, 0xf9, 0x2b, 0xef, 0xe1, 0x35, 0xda, 0xff, 0x72, 0x7e,
	0x4c, 0xd3, 0xdd, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7e, 0x8e, 0x53, 0x0c, 0x78, 0x01, 0x00,
	0x00,
}
